# Generated by Django 4.0.2 on 2022-03-09 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamdong', '0002_remove_electionvehiclegallery_main_flag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='electionvehiclegallery',
            name='title',
            field=models.CharField(db_column='title', default='', max_length=255),
        ),
    ]
