# Generated by Django 4.0.2 on 2022-03-09 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='title', max_length=255)),
                ('description', models.TextField(db_column='description')),
                ('path', models.CharField(db_column='path', max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성시간')),
            ],
            options={
                'db_table': 'election_vehicle',
            },
        ),
        migrations.CreateModel(
            name='ElectionVehicleGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_flag', models.CharField(db_column='main_flag', max_length=1)),
                ('path', models.CharField(db_column='path', max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성시간')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamdong.electionvehicle')),
            ],
            options={
                'db_table': 'election_vehicle_gallery',
            },
        ),
        migrations.CreateModel(
            name='ElectionVehicleDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(db_column='path', max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성시간')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamdong.electionvehicle')),
            ],
            options={
                'db_table': 'election_vehicle_detail',
            },
        ),
    ]
